server:
  port: 2222

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/usermanagement?useSSL=false
    username: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  mvc:
    view:
      prefix: /views/
      suffix: .jsp

app:
  messages:
    accountUnlockMessage: Your Account Successfully Unlock
    credentialInvalidMessage: Credentials are Invalid..Please Try again!!

